import json
import logging
from datetime import datetime
import os

class Reporter:
    def __init__(self, log_dir="logs"):
        self.log_dir = log_dir
        if not os.path.exists(log_dir):
            os.makedirs(log_dir)
            
        # Set up logger
        self.logger = logging.getLogger("WindowsMonitor")
        self.logger.setLevel(logging.INFO)
        
        # File handler
        log_file = os.path.join(self.log_dir, f"monitor_{datetime.now().strftime('%Y%m%d')}.log")
        fh = logging.FileHandler(log_file)
        fh.setLevel(logging.INFO)
        
        # Console handler
        ch = logging.StreamHandler()
        ch.setLevel(logging.INFO)
        
        formatter = logging.Formatter('%(asctime)s - %(levelname)s - %(message)s')
        fh.setFormatter(formatter)
        ch.setFormatter(formatter)
        
        # Avoid duplicate logs if instantiated multiple times
        if not self.logger.handlers:
            self.logger.addHandler(fh)
            self.logger.addHandler(ch)

    def log_alerts(self, alerts):
        """Logs a list of alerts generated by the analyzer."""
        for alert in alerts:
            severity = alert.get('severity', 'INFO')
            message = f"[{alert.get('type')}] {alert.get('message')}"
            
            if severity == 'HIGH':
                self.logger.warning(f"CRITICAL ALERT: {message}")
            elif severity == 'MEDIUM':
                self.logger.warning(f"WARNING: {message}")
            else:
                self.logger.info(message)
                
            # Log full details to a separate JSON file for reporting
            self._write_to_report(alert)
            
    def _write_to_report(self, alert):
        report_file = os.path.join(self.log_dir, "alerts_report.json")
        alert['timestamp'] = datetime.now().isoformat()
        
        existing_alerts = []
        if os.path.exists(report_file):
            try:
                with open(report_file, 'r') as f:
                    existing_alerts = json.load(f)
            except:
                pass
                
        existing_alerts.append(alert)
        
        with open(report_file, 'w') as f:
            json.dump(existing_alerts, f, indent=4)
